title: tlindsay42.github.io
name: Troy Lindsay

defaults:
  # _pages
  - scope:
      path: ""
      type: "pages"
    values:
      author_profile: true
      comments: true
      layout: "single"
      share: true
      toc: true
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      author_profile: true
      comments: true
      layout: "single"
      read_time: true
      related: true
      share: true

#theme: jekyll-theme-architect
theme: "minimal-mistakes-jekyll"
# remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum" "sunrise"

timezone: "America/Chicago"

plugins:
#   - jekyll-remote-theme
